title:            Nakamura Agatha
description:      A jekyll theme. Because I scribble.
url:              http://nakamuraapp.github.io
signoff:          Nakamura
disqus_shortname: nakamuraagatha
facebook_appid:   682990005109687
google_analytics: UA-21332781-7
links: 
  - name:         About
    url:          /about
  - name:         Project
    url:          /project
    external:     true
  - name:         Email
    url:          mailto:nakamura.agatha@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/nakamuraapp
    external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
permalink: /:title/


gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
