title:            Nakamura Agatha
description:      A jekyll theme. Because I scribble.
url:              http://nakamuraapp.github.io
signoff:          Nakamura
disqus_shortname: nakamuraagatha
facebook_appid:   604714799556697
google_analytics: UA-21332781-7
links: 
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://muan.co
    external:     true
  - name:         Email
    url:          mailto:hello@muan.co
    external:     true
  - name:         GitHub
    url:          http://github.com/muan
    external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
permalink: /:title/


gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
